"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_createExperimentPopup(object):
    def setupUi(self, createExperimentPopup):
        createExperimentPopup.setObjectName("createExperimentPopup")
        createExperimentPopup.resize(312, 94)
        self.pushButton = QtWidgets.QPushButton(parent=createExperimentPopup)
        self.pushButton.setGeometry(QtCore.QRect(60, 60, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=createExperimentPopup)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 60, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=createExperimentPopup)
        self.label.setGeometry(QtCore.QRect(40, 20, 111, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=createExperimentPopup)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 141, 22))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(createExperimentPopup)
        QtCore.QMetaObject.connectSlotsByName(createExperimentPopup)

    def retranslateUi(self, createExperimentPopup):
        _translate = QtCore.QCoreApplication.translate
        createExperimentPopup.setWindowTitle(_translate("createExperimentPopup", "Form"))
        self.pushButton.setText(_translate("createExperimentPopup", "Ok"))
        self.pushButton_2.setText(_translate("createExperimentPopup", "Cancel"))
        self.label.setText(_translate("createExperimentPopup", "Experiment Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    createExperimentPopup = QtWidgets.QWidget()
    ui = Ui_createExperimentPopup()
    ui.setupUi(createExperimentPopup)
    createExperimentPopup.show()
    sys.exit(app.exec())
