"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog.resize(784, 239)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-50, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(300, 20, 441, 205))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cronInput = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.cronInput.setObjectName("cronInput")
        self.gridLayout.addWidget(self.cronInput, 2, 1, 1, 1)
        self.localInput = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.localInput.setObjectName("localInput")
        self.gridLayout.addWidget(self.localInput, 0, 1, 1, 1)
        self.remoteInput = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.remoteInput.setObjectName("remoteInput")
        self.gridLayout.addWidget(self.remoteInput, 1, 1, 1, 1)
        self.copyFromBrowserButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.copyFromBrowserButton.setObjectName("copyFromBrowserButton")
        self.gridLayout.addWidget(self.copyFromBrowserButton, 1, 2, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 2, 1, 1)
        self.typeBox = QtWidgets.QGroupBox(Dialog)
        self.typeBox.setGeometry(QtCore.QRect(10, 20, 231, 101))
        self.typeBox.setObjectName("typeBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.typeBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 221, 76))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_3.setEnabled(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton.setEnabled(False)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Cron"))
        self.label_3.setText(_translate("Dialog", "Remote"))
        self.copyFromBrowserButton.setText(_translate("Dialog", "Copy from iRods Browser"))
        self.browseButton.setText(_translate("Dialog", "browse"))
        self.label_2.setText(_translate("Dialog", "Local"))
        self.comboBox.setItemText(0, _translate("Dialog", "Daily at midnight"))
        self.comboBox.setItemText(1, _translate("Dialog", "Daily at 1 pm"))
        self.comboBox.setItemText(2, _translate("Dialog", "Custom"))
        self.typeBox.setTitle(_translate("Dialog", "Type"))
        self.radioButton_2.setText(_translate("Dialog", "Scheduled upload"))
        self.radioButton_3.setText(_translate("Dialog", "One-way replication"))
        self.radioButton.setText(_translate("Dialog", "Two-way replication"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
