"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabNPECRules(object):
    def setupUi(self, tabNPECRules):
        tabNPECRules.setObjectName("tabNPECRules")
        tabNPECRules.resize(1114, 757)
        tabNPECRules.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    border-color: rgb(86, 184, 139);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QTabWidget\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"    border-color: rgb(86, 184, 139);\n"
"}\n"
"\n"
"QLabel#errorLabel\n"
"{\n"
"    color: rgb(217, 174, 23);\n"
"}\n"
"\n"
"QLineEdit#inputPath\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"    border-color: rgb(86, 184, 139);\n"
"}\n"
"\n"
"QPushButton#dataDeleteButton\n"
"{\n"
"    background-color: rgb(164, 0, 0);\n"
"    color: rgb(46, 52, 54);\n"
"}")
        self.tableWidget = QtWidgets.QTableWidget(parent=tabNPECRules)
        self.tableWidget.setGeometry(QtCore.QRect(90, 120, 841, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.pushButton = QtWidgets.QPushButton(parent=tabNPECRules)
        self.pushButton.setGeometry(QtCore.QRect(90, 330, 121, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=tabNPECRules)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 330, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=tabNPECRules)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 330, 111, 24))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(tabNPECRules)
        QtCore.QMetaObject.connectSlotsByName(tabNPECRules)

    def retranslateUi(self, tabNPECRules):
        _translate = QtCore.QCoreApplication.translate
        tabNPECRules.setWindowTitle(_translate("tabNPECRules", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("tabNPECRules", "Exp"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("tabNPECRules", "Path"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("tabNPECRules", "Users"))
        self.pushButton.setText(_translate("tabNPECRules", "Create experiment"))
        self.pushButton_2.setText(_translate("tabNPECRules", "Add users"))
        self.pushButton_3.setText(_translate("tabNPECRules", "Remove users"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabNPECRules = QtWidgets.QWidget()
    ui = Ui_tabNPECRules()
    ui.setupUi(tabNPECRules)
    tabNPECRules.show()
    sys.exit(app.exec())
