"""Created by: PyQt6 UI code generator from the corresponding UI file

WARNING: Any manual changes made to this file will be lost when pyuic6 is
run again.  Do not edit this file unless you know what you are doing.
"""


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabSynchronisation(object):
    def setupUi(self, tabSynchronisation):
        tabSynchronisation.setObjectName("tabSynchronisation")
        tabSynchronisation.resize(682, 712)
        tabSynchronisation.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    border-color: rgb(86, 184, 139);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"}\n"
"\n"
"QTabWidget\n"
"{\n"
"background-color: rgb(85, 87, 83);\n"
"}\n"
"\n"
"QTableWidget\n"
"{\n"
"background-color: rgb(85, 87, 83);\n"
"selection-background-color: rgb(58, 152, 112);\n"
"border-color: rgb(86, 184, 139);\n"
"}\n"
"\n"
"QLabel#errorLabel\n"
"{\n"
"color: rgb(217, 174, 23);\n"
"}\n"
"\n"
"QLineEdit#inputPath\n"
"{\n"
"background-color: rgb(85, 87, 83);\n"
"border-color: rgb(86, 184, 139);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#dataDeleteButton\n"
"{\n"
"background-color: rgb(164, 0, 0);\n"
"color: rgb(46, 52, 54);\n"
"}\n"
"\n"
"")
        self.create_configuration_button = QtWidgets.QPushButton(tabSynchronisation)
        self.create_configuration_button.setGeometry(QtCore.QRect(10, 300, 93, 28))
        self.create_configuration_button.setObjectName("create_configuration_button")
        self.update_configuration_button = QtWidgets.QPushButton(tabSynchronisation)
        self.update_configuration_button.setEnabled(False)
        self.update_configuration_button.setGeometry(QtCore.QRect(120, 300, 93, 28))
        self.update_configuration_button.setStyleSheet("QPushButton[enabled=true]{\n"
"color: rgb(86, 184, 139);\n"
"}\n"
"\n"
"QPushButton[enabled=false]{\n"
"color: rgb(117, 138, 122);\n"
"}")
        self.update_configuration_button.setObjectName("update_configuration_button")
        self.delete_configuration_button = QtWidgets.QPushButton(tabSynchronisation)
        self.delete_configuration_button.setEnabled(False)
        self.delete_configuration_button.setGeometry(QtCore.QRect(230, 300, 93, 28))
        self.delete_configuration_button.setStyleSheet("QPushButton[enabled=true]{\n"
"color: rgb(86, 184, 139);\n"
"}\n"
"\n"
"QPushButton[enabled=false]{\n"
"color: rgb(117, 138, 122);\n"
"}")
        self.delete_configuration_button.setObjectName("delete_configuration_button")
        self.event_view = QtWidgets.QTableView(tabSynchronisation)
        self.event_view.setGeometry(QtCore.QRect(10, 380, 641, 251))
        self.event_view.setObjectName("event_view")
        self.event_view.horizontalHeader().setDefaultSectionSize(250)
        self.force_trigger_button = QtWidgets.QPushButton(tabSynchronisation)
        self.force_trigger_button.setEnabled(False)
        self.force_trigger_button.setGeometry(QtCore.QRect(10, 640, 93, 28))
        self.force_trigger_button.setStyleSheet("QPushButton[enabled=true]{\n"
"color: rgb(86, 184, 139);\n"
"}\n"
"\n"
"QPushButton[enabled=false]{\n"
"color: rgb(117, 138, 122);\n"
"}")
        self.force_trigger_button.setObjectName("force_trigger_button")
        self.configuration_view = QtWidgets.QTableView(tabSynchronisation)
        self.configuration_view.setGeometry(QtCore.QRect(10, 20, 639, 279))
        self.configuration_view.setObjectName("configuration_view")
        self.event_view_label = QtWidgets.QLabel(tabSynchronisation)
        self.event_view_label.setGeometry(QtCore.QRect(20, 360, 120, 13))
        self.event_view_label.setObjectName("event_view_label")

        self.retranslateUi(tabSynchronisation)
        QtCore.QMetaObject.connectSlotsByName(tabSynchronisation)

    def retranslateUi(self, tabSynchronisation):
        _translate = QtCore.QCoreApplication.translate
        tabSynchronisation.setWindowTitle(_translate("tabSynchronisation", "Form"))
        self.create_configuration_button.setText(_translate("tabSynchronisation", "Create"))
        self.update_configuration_button.setText(_translate("tabSynchronisation", "Update"))
        self.delete_configuration_button.setText(_translate("tabSynchronisation", "Delete"))
        self.force_trigger_button.setText(_translate("tabSynchronisation", "force upload"))
        self.event_view_label.setText(_translate("tabSynchronisation", "Synchronisation events"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tabSynchronisation = QtWidgets.QWidget()
    ui = Ui_tabSynchronisation()
    ui.setupUi(tabSynchronisation)
    tabSynchronisation.show()
    sys.exit(app.exec())
