# This action is based on Github's default starter workflow for Python at
# https://github.com/actions/starter-workflows/blob/master/ci/python-package.yml
# (C) Github, MIT License

name: Python

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Aptmagic
      run: |
        sudo apt update
        sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
        sudo apt-get install -y python3-pyqt6.sip
        sudo apt-get install -y qt6-base-dev
        sudo apt-get install -y libgl1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --select=E999,F63,F7,F82,F831

    - name: Test with pytest
      run: |
        export QT_QPA_PLATFORM=offscreen
        pip install pytest
        pytest
